### ISSUE TITLE
How do I run the BeepBox Modded code?

### ISSUE THREAD

**Issue by StinkerB06** [Theepicosity/beepbox-modded#4]
How do you make a link with BeepBox running inside of it?

**Comment by Theepicosity** [comment]
you dont

**Comment by harrycode** [comment]
aaaand case close! XD

**Comment by harrycode** [comment]
oh and btw, use tags next time
;)

**Comment by StinkerB06** [comment]
I'm trying to make my fork (BruceBox) run in my browser!
